safe:                         true
future:                       true
lsi:                         false
auto:                        false
server:                      false
pygments:                    false
destination:               ./_site
baseurl:                   /kusar/
permalink: /blog/:year/:title.html

### # ###  Info om sidan ### # ###
description: En fin sida om h채star!
title: "Kusar: Fakta om h채star!"

### # ###  Info om sidan ### # ###
team:
  -
    name:  Jessica
    url:   http://jessan.github.com/
    duty:  Skriva om h채star
    locus: Sweden
  -
    name:  
    url:   http://
    duty:  
    locus: 
  -
    name:  Frank
    url:   http://knarf.se/
    duty:  Hj채lper till :D
    locus: Uppland, Sweden, Sol 3

