safe:                         true
future:                       true
lsi:                         false
auto:                        false
server:                      false
pygments:                    false
destination:               ./_site
baseurl:                   /kusar/
permalink: /blog/:year/:title.html
description: En fin sida om hästar!
title: "Kusar: Fakta om hästar!"
